try{
    throw "An excrption thst id thrown every tine";
}
catch(ex){
    console.log("Got an erorr!!!!!!!!!!!!!!");
    logError(ex);
}